'use strict';
/**
 * @module main/message
 * @summary Whiteflag JS main message module
 */
export {
    WfMessage,
    WfMessageData,
    WfMetaHeader,
    WfMetaField,
    getMessageType
};

/* Dependencies */
import { WfVersion, WfMsgType, WfMetaHeader, WfMessageData, WfMetaField, WfMsgField, WfRuntimeError, WfProtocolError, WfErrorCode, TransactionHash } from '@whiteflagprotocol/common';
import { WfCoreMessage, validateMessage } from '@whiteflagprotocol/core';
import { BinaryBuffer, ByteArray, Base64, DataId, Hex, Json, serializable, isSerializable, isObject } from '@whiteflagprotocol/util';
import { jsonToObj, b64ToStr, deepCopy } from '@whiteflagprotocol/util';

/* Constants */
/* The metaheader fields that cannot be altered once set */
const unalterableMeta = new Set(['autoGenerated', 'transactionHash']);

/* MODULE DECLARATIONS */
/**
 * A Whiteflag message as defined by the Whiteflag specification
 * @wfversion v1-draft.7
 * @wfreference 4 Message Format
 * @remarks This class extends the core Whiteflag message class by
 * adding metadata to the message, additional data conversions (such as to and
 * from JSON), and specific Whiteflag protocol features. This allows the class
 * to be used and integrated in larger functional applications in accordance
 * with the Whiteflag specification.
 */
class WfMessage extends WfCoreMessage {
    /* CLASS PROPERTIES */
    /** The data stored in this data item */
    readonly #data: WfMessageData;
    /** Reference to the message metaheader */
    readonly #meta: WfMetaHeader;
    /** The message transaction hash, or else a random id */
    #id: TransactionHash;

    /* CONSTRUCTOR */
    /**
     * Constructs a Whiteflag message
     * @param id a unique identifier for the data item; automatically generated if not specified
     * @param ddat a data acces stoken for access to the private data property
     */
    constructor(data: WfMessageData, binary?: BinaryBuffer, id?: DataId, ddat = Symbol('WfMessage')) {
        /* Organize core data */
        super(data, binary, id, ddat);

        /* References to data */
        this.#data = super.getDataReference(ddat) as WfMessageData;
        this.#meta = this.#data.MetaHeader;

        /* Set id: provided id, else metatdata, else (random) id from data item */
        this.#id = id || this.#meta[WfMetaField.TX_HASH] || super.id;
    }

    /* PUBLIC PROPERTY GETTERS */
    /**
     * Returns the unique id as a property
     */
    override get id(): TransactionHash {
        return this.#id;
    }

    /* STATIC FACTORY METHODS */
    /**
     * Creates a new Whiteflag message
     * @param type the Whiteflag message type
     * @param version the Whiteflag protocol version
     * @param txHash the transaction hash identifying the message
     * @returns a new Whiteflag message of the specified type
     */
    public static override create(type: string, version: string = '1', txHash?: TransactionHash): WfMessage {
        const meta = checkMetaHeader(Object.create(null), txHash);
        const data = {
            MetaHeader: meta,
            MessageHeader: super.generateHeader(type as WfMsgType, version as WfVersion),
            MessageBody: super.generateBody(type as WfMsgType, version as WfVersion)
        }
        return new this(data, BinaryBuffer.empty(), txHash);
    }
    /**
     * Deserializes the message data
     * @param data the base64 encoded JSON serialized originator data
     * @param txHash the transaction hash identifying the message
     * @returns the Whiteflag message
     */
    public static override deserialize(data: Base64, txHash: TransactionHash): WfMessage {
        return this.fromJson(b64ToStr(data), txHash);
    }
    /**
     * Creates new Whiteflag message from a JSON serialized object
     * @param message the JSON serialized object
     * @param txHash the transaction hash identifying the message
     * @returns a new Whiteflag message
     */
    public static override fromJson(message: Json, txHash?: TransactionHash): WfMessage {
        return this.fromObject(jsonToObj(message) as WfMessageData, txHash);
    }
    /**
     * Creates new Whiteflag message from a plain message data object
     * @param message a plain JavaScript object with a Whiteflag message
     * @param txHash the transaction hash identifying the message, if known
     * @returns a new Whiteflag message
     */
    public static override fromObject(message: WfMessageData, txHash?: TransactionHash): WfMessage {
        /* Check object for errors */
        const errors = validateMessage(message);
        if (errors.length > 0) throw new WfProtocolError('Invalid message', errors, WfErrorCode.FORMAT);

        /* Check metaheader and transaction hash */
        message.MetaHeader = checkMetaHeader(message.MetaHeader, txHash);

        /* Create new WfCoreMessage object */
        const wfMessage = this.create(
            message.MessageHeader[WfMsgField.H_MSGCODE] as WfMsgType,
            message.MessageHeader[WfMsgField.H_VERSION] as WfVersion,
            txHash || message.MetaHeader[WfMetaField.TX_HASH]
        );
        /* Set message segments, and return result */
        wfMessage.setHeader(message.MessageHeader);
        wfMessage.setBody(message.MessageBody);
        wfMessage.setMetaHeader(message.MetaHeader);
        return wfMessage;
    }
    /**
     * Creates new Whiteflag message from a binary buffer
     * @param message a binary buffer with the encoded message
     * @param txHash the transaction hash identifying the message, if known
     * @returns a new Whiteflag message
     * @remarks The message will not yet be decrypted/decode
     */
    public static override fromBinary(message: BinaryBuffer, txHash?: TransactionHash): WfMessage {
        /* Construct data */
        const header = this.extractHeader(message);
        const meta = checkMetaHeader(Object.create(null), txHash);
        const data = {
            MetaHeader: meta,
            MessageHeader: header,
            MessageBody: this.generateBody(WfMsgType.unknown, header[WfMsgField.H_VERSION] as WfVersion)
        }
        /* Create message */
        return new this(data, message, txHash);
    }
    /**
     * Creates new Whiteflag message from a hexadecimal encoded string
     * @param message  atring with the hexadecimal encoded message
     * @param txHash the transaction hash identifying the message, if known
     * @returns a new Whiteflag message
     * @remarks The message will not yet be decrypted/decode
     */
    public static fromHex(message: Hex, txHash?: TransactionHash): WfMessage {
        return this.fromBinary(BinaryBuffer.fromHex(message), txHash);
    }
    /**
     * Creates new Whiteflag message from a binary encoded message
     * @param message a ByteArray with the binary encoded message
     * @param txHash the transaction hash identifying the message, if known
     * @returns a new Whiteflag message object
     * @remarks The message will not yet be decrypted/decode
     */
    public static fromU8a(message: ByteArray, txHash?: TransactionHash): WfMessage {
        return this.fromBinary(BinaryBuffer.fromU8a(message), txHash);
    }

    /* PUBLIC CLASS METHODS */
    /**
     * Gives the message type
     * @returns a string with the message type, reference indicator and subject code
     */
    public getType(): string {
        return getMessageType(this);
    }
    /**
     * Returns the value of the specified metaheader field
     * @param fieldName the name of the metaheader field
     * @returns the value of the metaheader field
     */
    public getMeta(fieldName: string): serializable {
        /* Look for field value in metaheader */
        if (Object.hasOwn(this.#meta, fieldName)) {
            if (this.#meta[fieldName]) return this.#meta[fieldName];
        }
        /* Specified field not found or null */
        return null;
    }
    /**
     * Sets the value of the specified metaheader field
     * @param fieldName the name of the metaheader field
     * @param value the value to set, which must be a string or a number
     * @returns `true` if succesful, else `false`, e.g. when field may not be altered
     * @remarks If the `transactionHash` metadata field is set, it also sets
     * the data item identifier to the same value autmatically. Some metadata
     * fields may be set only once and cannot be altered.
     */
    public setMeta(fieldName: string, value: serializable): boolean {
        /* Check value */
        if (!isSerializable(value)) return false;

        /* Set field value after check if field may not be altered once set */
        if (Object.hasOwn(this.#meta, fieldName) && !!this.#meta[fieldName]) {
            if (unalterableMeta.has(fieldName)) return false;
        }
        this.#meta[fieldName] = value;

        /* Use transaction hash as message id */
        if (fieldName === WfMetaField.TX_HASH) {
            if (typeof value === 'string') this.#id = value;
        }
        /* All done */
        return true;
    }
    /**
     * Returns the message metaheader
     * @returns a plain object with the message metaheader
     */
    public getMetaHeader(): WfMetaHeader {
        return deepCopy(this.#meta);
    }
    /**
     * Sets the values of metaheader fields
     * @param meta a Whiteflag message metaheader
     */
    public setMetaHeader(meta: WfMetaHeader): boolean {
        for (const [field, value] of Object.entries(meta)) {
            this.setMeta(field, value as serializable);
        }
        return true;
    }
}

/* PRIVATE MODULE FUNCTIONS */
/**
 * Determines the message type
 * @param message a Whiteflag message
 * @returns a string with the message type, reference indicator and subject code
 */
function getMessageType(message: WfMessage): string {
    /* Check for message code */
    if (!message.type) return 'unknown';

    /* Check message details */
    let reference = ''
    let subject = '';
    if (message.type !== WfMsgType.T) {
        /* Check reference indicator */
        const ri = message.getHeaderField(WfMsgField.H_REFERENCEIND);
        reference = ri ? `(${ri})` : '';

        /* Check subject code or equivalent */
        const sc = message.getBodyField(WfMsgField.SUBJECTCODE);
        const cd = message.getBodyField(WfMsgField.CRYPTDATATYPE);
        const vm = message.getBodyField(WfMsgField.VERIFICATIONMTD);
        const rm = message.getBodyField(WfMsgField.REFERENCEMTD);
        subject = sc || cd || vm || rm || '';
    }
    /* Compile message type string */
    return `${message.type}${subject}${reference}`;
}
/**
 * Checks if metaheader exists and if it corresponds with the transaction hash
 * @param meta the metaheader of the message
 * @param txHash the transaction hash of the message
 * @returns the updated metaheader of the message
 */
function checkMetaHeader(meta: WfMetaHeader | undefined, txHash?: TransactionHash): WfMetaHeader {
    /* Create empty metaheader if not existing */
    if (!isObject(meta)) {
        meta = Object.create(null) as WfMetaHeader;
    }
    /* Check transactionHash */
    if (txHash) {
        if (!meta.transactionHash) {
            meta.transactionHash = txHash;
        } else if (meta.transactionHash !== txHash) {
            throw new WfRuntimeError(`Message transaction hash ${meta.transactionHash} does not match message identifier ${txHash}`);
        }
    }
    return meta;
}
