'use strict';
/**
 * @module main/message
 * @summary Whiteflag JS main message module
 */
export {
    WfMessage,
    WfMessageData,
    WfMetaHeader,
    WfMetaField,
    getMessageType
};

/* Dependencies */
import { WfVersion, WfMsgType, WfRuntimeError, WfProtocolError, WfErrorCode, TransactionHash } from '@whiteflagprotocol/common';
import { WfCoreMessage, WfCoreMessageData, validateMessage } from '@whiteflagprotocol/core';
import { BinaryBuffer, ByteArray, Base64, DataId, Hex, Iso8601, Json, Serializable, serializable, isSerializable, isObject } from '@whiteflagprotocol/util';
import { deepCopy, jsonToObj, b64ToStr } from '@whiteflagprotocol/util';

/* Constants */
/* Metaheader fields that cannot be altered once set */
const unalterableMeta = new Set(['autoGenerated', 'transactionHash']);

/* MODULE DECLARATIONS */
/**
 * Whiteflag message data structure as used by the `WfMessage` class
 */
interface WfMessageData extends WfCoreMessageData {
    /** The metaheader of the Whiteflag message */
    MetaHeader: WfMetaHeader;
}
/**
 * A Whiteflag message as defined by the Whiteflag specification
 * @wfversion v1-draft.7
 * @wfreference 4 Message Format
 * @remarks This class extends the core Whiteflag message class by
 * adding metadata to the message, additional data conversions (such as to and
 * from JSON), and specific Whiteflag protocol features. This allows the class
 * to be used and integrated in larger functional applications in accordance
 * with the Whiteflag specification.
 */
class WfMessage extends WfCoreMessage {
    /* CLASS PROPERTIES */
    /** The data stored in this data item */
    readonly #data: WfMessageData;
    /** Reference to the message metaheader */
    readonly #meta: WfMetaHeader;
    /** The message transaction hash, or else a random id */
    #id: TransactionHash;

    /* CONSTRUCTOR */
    /**
     * Constructs a Whiteflag message
     * @param id a unique identifier for the data item; automatically generated if not specified
     * @param ddat a data acces stoken for access to the private data property
     */
    constructor(data: WfMessageData, binary?: BinaryBuffer, id?: DataId, ddat = Symbol('WfMessage')) {
        /* Organize core data */
        super(data, binary, id, ddat);

        /* References to data */
        this.#data = super.getDataReference(ddat) as WfMessageData;
        this.#meta = this.#data.MetaHeader;
        this.#id = super.id;
    }

    /* PUBLIC PROPERTY GETTERS */
    /**
     * Returns the unique id as a property
     */
    override get id(): TransactionHash {
        return this.#id;
    }

    /* STATIC FACTORY METHODS */
    /**
     * Creates a new Whiteflag message
     * @param type the Whiteflag message type
     * @param version the Whiteflag protocol version
     * @returns a new Whiteflag message of the specified type
     */
    public static override create(type: string, version: string = '1'): WfMessage {
        const data = {
            MetaHeader: Object.create(null),
            MessageHeader: super.generateHeader(type as WfMsgType, version as WfVersion),
            MessageBody: super.generateBody(type as WfMsgType, version as WfVersion)
        }
        return new this(data);
    }
    /**
     * Deserializes the message data
     * @param data the base64 encoded JSON serialized originator data
     * @param txHash the transaction hash identifying the message
     * @returns the Whiteflag message
     */
    public static override deserialize(data: Base64, txHash: Hex): WfMessage {
        return this.fromJson(b64ToStr(data), txHash);
    }
    /**
     * Creates new Whiteflag message from a JSON serialized object
     * @param message the JSON serialized object
     * @param txHash the transaction hash identifying the message
     * @returns a new Whiteflag message
     */
    public static override fromJson(message: Json, txHash?: Hex): WfMessage {
        return this.fromObject(jsonToObj(message) as WfMessageData, txHash);
    }
    /**
     * Creates new Whiteflag message from a plain message data object
     * @param message a plain JavaScript object with a Whiteflag message
     * @param txHash the transaction hash identifying the message
     * @returns a new Whiteflag message
     */
    public static override fromObject(message: WfMessageData, txHash?: Hex): WfMessage {
        /* Check object */
        const errors = validateMessage(message);
        if (errors.length > 0) throw new WfProtocolError('Invalid message', errors, WfErrorCode.FORMAT);
        if (!isObject(message.MetaHeader)) {
            message.MetaHeader = Object.create(null);
        }
        /* Check identifier */
        if (txHash) {
            if (!message.MetaHeader.transactionHash) {
                message.MetaHeader.transactionHash = txHash;
            } else if (message.MetaHeader.transactionHash !== txHash) {
                throw new WfRuntimeError(`Message transaction hash ${message.MetaHeader.transactionHash} does not match message identifier ${txHash}`);
            }
        }
        /* Create new WfCoreMessage object */
        const wfMessage = this.create(
            message.MessageHeader['MessageCode'] as WfMsgType,
            message.MessageHeader['Version'] as WfVersion
        );
        /* Set message segments, and return result */
        wfMessage.setHeader(message.MessageHeader);
        wfMessage.setBody(message.MessageBody);
        wfMessage.setMetaHeader(message.MetaHeader);
        return wfMessage;
    }
    /**
     * Creates new Whiteflag message from a binary buffer
     * @param message a binary buffer with the encoded message
     * @returns a new Whiteflag message
     * @remarks The message will not yet be decrypted/decode
     */
    public static override fromBinary(message: BinaryBuffer): WfMessage {
        /* Construct data */
        const header = this.extractHeader(message);
        const data = {
            MetaHeader: Object.create(null),
            MessageHeader: header,
            MessageBody: this.generateBody(WfMsgType.unknown, header['version'] as WfVersion)
        }
        /* Create message */
        return new this(data, message);
    }
    /**
     * Creates new Whiteflag message from a hexadecimal encoded string
     * @param message  atring with the hexadecimal encoded message
     * @returns a new Whiteflag message
     * @remarks The message will not yet be decrypted/decode
     */
    public static fromHex(message: Hex): WfMessage {
        return this.fromBinary(BinaryBuffer.fromHex(message));
    }
    /**
     * Creates new Whiteflag message from a binary encoded message
     * @param message a ByteArray with the binary encoded message
     * @returns a new Whiteflag message object
     * @remarks The message will not yet be decrypted/decode
     */
    public static fromU8a(message: ByteArray): WfMessage {
        return this.fromBinary(BinaryBuffer.fromU8a(message));
    }

    /* PUBLIC CLASS METHODS */
    /**
     * Gives the message type
     * @returns a string with the message type, reference indicator and subject code
     */
    public getType(): string {
        return getMessageType(this);
    }
    /**
     * Returns the value of the specified metaheader field
     * @param fieldName the name of the metaheader field
     * @returns the value of the metaheader field
     */
    public getMeta(fieldName: string): serializable {
        /* Look for field value in metaheader */
        if (Object.hasOwn(this.#meta, fieldName)) {
            if (this.#meta[fieldName]) return this.#meta[fieldName];
        }
        /* Specified field not found or null */
        return null;
    }
    /**
     * Sets the value of the specified metaheader field
     * @param fieldName the name of the metaheader field
     * @param value the value to set, which must be a string or a number
     * @returns `true` if succesful, else `false`, e.g. when field may not be altered
     * @remarks If the `transactionHash` metadata field is set, it also sets
     * the data item identifier to the same value autmatically. Some metadata
     * fields may be set only once and cannot be altered.
     */
    public setMeta(fieldName: string, value: serializable): boolean {
        /* Check value */
        if (!isSerializable(value)) return false;

        /* Check if field may not be altered once set */
        if (Object.hasOwn(this.#meta, fieldName) && !!this.#meta[fieldName]) {
            if (unalterableMeta.has(fieldName)) return false;
        }
        /* Set field value */
        this.#meta[fieldName] = value;
        if (fieldName === 'transactionHash') {
            if (typeof value === 'string') this.#id = value;
        }
        return true;
    }
    /**
     * Returns the message metaheader
     * @returns a plain object with the message metaheader
     */
    public getMetaHeader(): WfMetaHeader {
        return deepCopy(this.#meta);
    }
    /**
     * Sets the values of metaheader fields
     * @param meta a Whiteflag message metaheader
     */
    public setMetaHeader(meta: WfMetaHeader): boolean {
        for (const [field, value]  of Object.entries(meta)) {
            if (!this.setMeta(field, value as any)) {
                throw new WfProtocolError(`Metaheader field ${field} could not be set`, null, WfErrorCode.METAHEADER);
            }
        }
        return true;
    }
}

/* MODULE DECLARATIONS */
/**
 * Whiteflag message metaheader fields as used by the WFJSL
 */
enum WfMetaField {
    /** Indicates if the message has been
     * automatically generated */
    AUTOGEN = 'autoGenerated',
    /** The name identifying the underlying blockchain */
    BLOCKCHAIN = 'blockchain',
    /** Indicates' if this message is to be transmitted (TX) to the
     * blockchain or has been received (RX) from the blockchain */
    TX_DIRECTION = 'transceiveDirection',
    /** Indicates if message was succesfully put into a
     * blockchain transaction */
    TX_SUCCESS = 'transmissionSuccess',
    /** The hash of the transaction containing the Whiteflag message,
     * encoded as specified for the blockchain */
    TX_HASH = 'transactionHash',
    /** The timestamp of the message transaction or block
     * containing the Whiteflag message */
    TX_TIME = 'transactionTime',
    /** The index of the message transaction in a block */
    TX_INDEX = 'transactionIndex',
    /** The number of the block the message transaction is in */
    BLOCK_NR = 'blockNumber',
    /** The number of blocks from current block where transaction
     * is in, * until the confirmation maximum is reached */
    BLOCK_DEPTH = 'blockDepth',
    /** Indication whether the message is confirmed,
     * i.e. the minimal block depth has been reached */
    CONFIRMED = 'confirmed',
    /** The address of the blockchain account to which
     * the message is sent (required to determine encryption key) */
    RECIPIENT_ADDR = 'recipientAddress',
    /** The address of the blockchain account from which
     * the message is sent */
    ORIGINATOR_ADDR = 'originatorAddress',
    /** The public key of the blockchain account from which
     * the message is sent */
    ORIGINATOR_PUBKEY = 'originatorPubKey',
    /** Indicates if a valid A-message preceded this message,
     * or if it is itself a valid A-message */
    ORIGINATOR_VALID = 'originatorValid',
    /** Indicates if this messages references other
     * messages correctly */
    REFERENCE_VALID = 'referenceValid',
    /** Indicates if the message complies with the
     * Whiteflag specification */
    FORMAT_VALID = 'formatValid',
    /** Message validation errors */
    ERRORS = 'validationErrors',
    /** The hexadecimal representation of the message
     * in compressed binary encoding, optionally encrypted */
    ENCODED = 'encodedMessage',
    /** The hexadecimal representation of the initialization
     * vector of an encrypted message */
    CRYPTO_IV = 'encryptionInitVector',
    /** The hexadecimal representation of the secret from which
     * the encryption key is derived */
    CRYPTO_IKM = 'encryptionKeyInput'
}
/**
 * Whiteflag message metaheader
 * @remarks The metaheader is not defined by the Whiteflag specification. The
 * entries defined here are the ones as used by Whiteflag JS.
 */
interface WfMetaHeader extends Serializable {
    /** Any meta property is allowed, but value types are restructed to
     *  strings, array of strings, numbers, booleans, null and undefined */
    [key: string]: serializable | undefined;
    /** Indicates if the message has been
     * automatically generated */
    [WfMetaField.AUTOGEN]?: string;
    /** The name identifying the underlying blockchain */
    [WfMetaField.BLOCKCHAIN]?: string;
    /** Indicates if this message is to be transmitted (TX) to the
     * blockchain or has been received (RX) from the blockchain */
    [WfMetaField.TX_DIRECTION]?: string;
    /** Indicates if message was succesfully put into a
     * blockchain transaction */
    [WfMetaField.TX_SUCCESS]?: boolean;
    /** The hash of the transaction containing the Whiteflag message,
     * encoded as specified for the blockchain */
    [WfMetaField.TX_HASH]?: string;
    /** The timestamp of the message transaction or block
     * containing the Whiteflag message */
    [WfMetaField.TX_TIME]?: Iso8601;
    /** The index of the message transaction in a block */
    [WfMetaField.TX_INDEX]?: number;
    /** The number of the block the message transaction is in */
    [WfMetaField.BLOCK_NR]?: number;
    /** The number of blocks from current block where transaction
     * is in, * until the confirmation maximum is reached */
    [WfMetaField.BLOCK_DEPTH]?: number;
    /** Indication whether the message is confirmed,
     * i.e. the minimal block depth has been reached */
    [WfMetaField.CONFIRMED]?: boolean;
    /** The address of the blockchain account to which
     * the message is sent (required to determine encryption key) */
    [WfMetaField.RECIPIENT_ADDR]?: string;
    /** The address of the blockchain account from which
     * the message is sent */
    [WfMetaField.ORIGINATOR_ADDR]?: string;
    /** The public key of the blockchain account from which
     * the message is sent */
    [WfMetaField.ORIGINATOR_PUBKEY]?: Hex;
    /** Indicates if a valid A-message preceded this message,
     * or if it is itself a valid A-message */
    [WfMetaField.ORIGINATOR_VALID]?: boolean;
    /** Indicates if this messages references other
     * messages correctly */
    [WfMetaField.REFERENCE_VALID]?: boolean;
    /** Indicates if the message complies with the
     * Whiteflag specification */
    [WfMetaField.FORMAT_VALID]?: boolean;
    /** Message validation errors */
    [WfMetaField.ERRORS]?: string[];
    /** The hexadecimal representation of the message
     * in compressed binary encoding, optionally encrypted */
    [WfMetaField.ENCODED]?: Hex;
    /** The hexadecimal representation of the initialization
     * vector of an encrypted message */
    [WfMetaField.CRYPTO_IV]?: Hex;
    /** The hexadecimal representation of the secret from which
     * the encryption key is derived */
    [WfMetaField.CRYPTO_IKM]?: Hex;
}

/* PRIVATE MODULE FUNCTIONS */
/**
 * Determines the message type
 * @param message a Whiteflag message
 * @returns a string with the message type, reference indicator and subject code
 */
function getMessageType(message: WfMessage): string {
    /* Check for message code */
    const type = message.getHeaderField('MessageCode');
    if (!type) return 'unknown';

    /* Check message details */
    let reference = ''
    let subject = '';
    if (type !== WfMsgType.T) {
        /* Check reference indicator */
        const ri = message.getHeaderField('ReferenceIndicator');
        reference = ri ? `(${ri})` : '';

        /* Check subject code or equivalent */
        const sc = message.getBodyField('SubjectCode');
        const cd = message.getBodyField('CryptoDataType');
        const vm = message.getBodyField('VerificationMethod');
        const rm = message.getBodyField('ResourceMethod');
        subject = sc || cd || vm || rm || '';
    }
    /* Check encryption */
    let EB = ''; let EE = '';
    if (message.getHeaderField('EncryptionIndicator') !== '0') {
        EB = '['; EE = ']';
    }
    /* Compile message type string */
    return `${EB}${type}${subject}${reference}${EE}`;
}
