'use strict';
/**
 * @module main/message
 * @summary Whiteflag JS message class
 */
export {
    WfMessage,
    WfMetaHeader
};

/* Module imports */
import {
    WfVersion,
    WfMsgType,
    WfCoreMessage
} from '@whiteflagprotocol/core';

/**
 * A Whiteflag message as defined by the Whiteflag specification
 * @class WfMessage
 * @wfversion v1-draft.7
 * @wfreference 4 Message Format
 * @remarks This class extends the core Whiteflag message class by
 * adding metadata to the message, additional data conversions (such as to and
 * from JSON), and specific Whiteflag protocol features. This allows the class
 * to be used and integrated in larger functional applications in accordance
 * with the Whiteflag specification.
 */
class WfMessage extends WfCoreMessage {
    /* CLASS PROPERTIES */

    /** The message metadata required for processing the message */
    protected meta: WfMetaHeader = {};

    /* CONSTRUCTOR */
    /**
     * Constructor for a Whiteflag message
     * @param type the Whiteflag message type
     * @param version the Whiteflag protocol version
     */
    constructor(type: string, version: string = '1') {
        super(type as WfMsgType, version as WfVersion);
    }

    /* STATIC FACTORY METHODS */
    /**
     * Creates new Whiteflag message from a plain object
     * @function fromObject
     * @param message a plain JavaScript object with message header and body
     * @returns a new Whiteflag message
     * @throws {WfProtocolError} if message could not be created
     */
    public static async fromJSON(message: string): Promise<WfMessage> {
        const wfMessage = await this.fromObject(JSON.parse(message));
        return wfMessage as WfMessage;
    }

    /* PUBLIC CLASS METHODS */
    /**
     * Returns the value of the metaheader field
     * @function getMeta
     * @param fieldName the name of the metaheader field
     * @returns the value of the metaheader field
     */
    public getMeta(fieldName: string): string | null {
        /* Look for field in metaheader */
        for (const field of Object.keys(this.meta)) {
            if (field === fieldName) return this.meta[field];
        }
        /* Specified field not found */
        return null;
    }
    /**
     * Sets the value of the specified metaheader field
     * @function setMeta
     * @param fieldName the name of the metaheader field
     * @param value the value to set
     * @return true if succesful, else false
     */
    public setMeta(fieldName: string, value: string): boolean {
        this.meta[fieldName] = value;
        return true;
    }
    /**
     * Returns the Whiteflag message as a plain object
     * @function toObject
     * @returns the message as a plain object
     */
    public toObject(): Object {
        let message = super.toObject() as any;
        message.MetaHeader = this.meta;
        return message;
    }
    /**
     * Returns the Whiteflag message as a plain object
     * @function toObject
     * @returns the message as a plain object
     */
    public toJSON(): string {
        return JSON.stringify(this.toObject());
    }
}

/* MODULE DECLARATIONS */
/**
 * Defines a Whiteflag message header object
 * @interface WfMetaHeader
 */
interface WfMetaHeader {
    /* Metaheader may include custom properties */
    [key: string]: any,
    /* Fields used by the Whiteflag software */
    autoGenerated?: string,
    blockchain?: string
    transceiveDirection?: string,
    transmissionSuccess?: boolean,
    transactionHash?: string,
    transactionTime?: string,
    transactionIndex?: number,
    blockNumber?: number,
    blockDepth?: number,
    confirmed?: boolean,
    recipientAddress?: string,
    originatorAddress?: string,
    originatorPubKey?: string,
    originatorValid?: boolean,
    referenceValid?: boolean,
    formatValid?: boolean,
    validationErrors?: string[],
    encodedMessage?: string,
    encryptionInitVector?: string,
    encryptionKeyInput?: string
}
