/**
 * @module core/message
 * @summary Whiteflag JS message class
 * @since v1.0 (Whiteflag specification v1-draft.7)
 */
export { WfMessage };

/* Whiteflag static message structures */
import v1 from '../static/v1/wf-msg-structure.json' with { type: 'json' };

/* MODULE DECLARATIONS */
/**
 * Defines Whiteflag message types
 * @enum WfFieldType
 */
enum WfMsgType {
    A = 'A',
    K = 'K',
    T = 'T',
    P = 'P',
    D = 'D',
    S = 'S',
    E = 'E',
    I = 'I',
    M = 'M',
    Q = 'Q',
    R = 'R',
    F = 'F'
}
/**
 * Defines Whiteflag fields
 */
const MSG = compileMsgStructure();

/**
 * Whiteflag Message
 * @class WfMessage
 */
class WfMessage {
    /* CLASS PROPERTIES */
    /**
     * @property {Object} MetaHeader The meta header
     */
    public MetaHeader: WfMetaHeader;
    /**
     * @property {Object} MessageHeader The message header
     */
    public MessageHeader: WfMsgHeader;
    /**
     * @property {Object} MessageBody The message body
     */
    public MessageBody: WfMsgBody;

    /* CONSTRUCTOR */
    /**
     * Constructor for a Whiteflag message
     * @param wfMsgType the Whiteflag message type
     * @param wfVersion the version of the used Whiteflag specification
     */
    constructor(wfMsgType: WfMsgType, wfVersion: number = 1) {
        /* Properties */
        this.MetaHeader = {};
        this.MessageHeader = {};
        this.MessageBody = {};

        /* Generate message header */
        for (const fieldName of Object.keys(MSG[wfMsgType][wfVersion].header)) {
            this.MessageHeader[fieldName] = '';
        }
        this.MessageHeader.Version = wfVersion.toString();
        this.MessageHeader.MessageCode = wfMsgType as string;

        /* Generate message body */
        for (const fieldName of Object.keys(MSG[wfMsgType][wfVersion].body)) {
            this.MessageBody[fieldName] = '';
        }
    }

    /* STATIC FACTORY METHODS */
    /* @todo: develop static factory methods */
    public static fromObject(wfMessage: any): WfMessage {
        return new WfMessage(wfMessage?.MessageHeader?.MessageCode, wfMessage?.MessageHeader?.Version);
    }

    /* PUBLIC CLASS METHODS */
    /* @todo: develop class functions */
    public isValid() {}
    public encode() {}
    public get() {}
    public set() {}
    public toObject() {}
    public toHex() {}
    public toU8a() {}
}

/* PRIVATE MODULE DECLARATIONS */
/**
 * Defines a Whiteflag message header object
 * @private
 * @interface WfMsgHeader
 */
interface WfMetaHeader {
    /* Metaheader may include custom properties */
    [key: string]: any,
    /* Fields used by the Whiteflag software */
    autoGenerated?: string,
    blockchain?: string
    transceiveDirection?: string,
    transmissionSuccess?: boolean,
    transactionHash?: string,
    transactionTime?: string,
    transactionIndex?: number,
    blockNumber?: number,
    blockDepth?: number,
    confirmed?: boolean,
    recipientAddress?: string,
    originatorAddress?: string,
    originatorPubKey?: string,
    originatorValid?: boolean,
    referenceValid?: boolean,
    formatValid?: boolean,
    validationErrors?: string[],
    encodedMessage?: string,
    encryptionInitVector?: string,
    encryptionKeyInput?: string
}
/**
 * Defines a Whiteflag message header object
 * @private
 * @interface WfMsgHeader
 */
interface WfMsgHeader {
    /* Required for dynamic creation */
    [key: string]: any,
    /* Defined header fields
     * for all versions */
    Prefix?: string,
    Version?: string,
    EncryptionIndicator?: string,
    DuressIndicator?: string,
    MessageCode?: string,
    ReferenceIndicator?: string,
    ReferencedMessage?: string,
}
/**
 * Defines a Whiteflag message header object
 * @private
 * @interface WfMsgHeader
 */
interface WfMsgBody {
    /* Required for dynamic creation */
    [key: string]: any,
    /* Defined body fields
     * for all versions and message types */
    VerificationMethod?: string,
    VerificationData?: string,
    CryptoDataType?: string,
    CryptoData?: string,
    SubjectCode?: string,
    DateTime?: string,
    Duration?: string,
    ObjectType?: string,
    ObjectLatitude?: string,
    ObjectLongitude?: string,
    ObjectSizeDim1?: string,
    ObjectSizeDim2?: string,
    ObjectOrientation?: string,
    ResourceMethod?: string,
    ResourceData?: string,
    Text?: string
}
/**
 * Defines an object with field type definitions
 * @private
 * @interface WfMsgStructure
 */
interface WfMsgStructure {
    [key: string]: {    // Message type
        [key: number]: {    // Whiteflag version
            header: {
                [key: string]: {    // Message header field with start bit
                    encoding: string,
                    startBit: number,
                    endBit: number
                }   
            },
            body: {
                [key: string]: {    // Message body field with start bit
                    encoding: string,
                    startBit: number
                }
            }
        }
    }
}
/**
 * Compiles an object with all valid field type definitions
 * @private
 * @returns an object with field type definitions
 */
function compileMsgStructure(): WfMsgStructure {
    const SIGNSIGNALTYPE = '$signsignal';
    const msgStructure: WfMsgStructure = {};
    for (const type of Object.values(WfMsgType)) {
        msgStructure[type] = {};

        /* Currently, there is only one Whiteflag version */
        msgStructure[type][1] = { header:{}, body: {} };
        msgStructure[type][1].header = v1.header;
        if (Object.keys(v1.body[type]).includes(SIGNSIGNALTYPE)) {
            msgStructure[type][1].body = v1.body[SIGNSIGNALTYPE];
        } else {
            msgStructure[type][1].body = v1.body[type] as any;
        }
    }
    return msgStructure;
}
